//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.AccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ContractData()
        {
            this.Warranty = new HashSet<Warranty>();
        }
    
        public int Id { get; set; }
        public string ContractNumber { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> ContractStatusId { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedAt { get; set; }
        public string Path { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string Note { get; set; }
        public Nullable<int> BankId { get; set; }
        public Nullable<int> SectorId { get; set; }
        public Nullable<int> AdministrationId { get; set; }
    
        public virtual Administration Administration { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Bank Bank { get; set; }
        public virtual Company Company { get; set; }
        public virtual ContractStatus ContractStatus { get; set; }
        public virtual Sector Sector { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Warranty> Warranty { get; set; }
    }
}
