//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.AccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class WarrantyHistory
    {
        public int Id { get; set; }
        public Nullable<int> WarrantyId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedAt { get; set; }
        public string Path { get; set; }
        public Nullable<int> GuaranteeStatusId { get; set; }
        public Nullable<int> GuaranteeSortId { get; set; }
        public Nullable<System.DateTime> GuaranteeIssueDate { get; set; }
        public string WarrantyNumber { get; set; }
        public Nullable<decimal> WarrantyValue { get; set; }
        public Nullable<int> WarrantyTypeId { get; set; }
        public Nullable<System.DateTime> GuaranteeStartDate { get; set; }
        public Nullable<System.DateTime> GuaranteeEndDate { get; set; }
        public string NoteWarrantyHistory { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<int> DecreaseOrIncreaseId { get; set; }
        public Nullable<decimal> DecreaseOrIncreaseValue { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual DecreaseOrIncrease DecreaseOrIncrease { get; set; }
        public virtual GuaranteeSort GuaranteeSort { get; set; }
        public virtual GuaranteeStatus GuaranteeStatus { get; set; }
        public virtual Warranty Warranty { get; set; }
        public virtual WarrantyType WarrantyType { get; set; }
    }
}
